imports:
    - { resource: config.yml }

framework:
    router:
        strict_requirements: true

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: notice
            channels: [!event]
        detailed:
           type: stream
           path: "%kernel.logs_dir%/%kernel.environment%_debug.log"
           level: debug
           channels: [!event]
        event:
           type: stream
           path: "%kernel.logs_dir%/%kernel.environment%_debug_event.log"
           level: debug
